/**
 * facilities.ts — Government health facilities in 6 NCR-adjacent districts
 * Source: NHM Haryana, NHM Uttar Pradesh, data.gov.in
 * // TODO(backend): GET /api/v1/facilities
 */

import type { Facility } from '@/types';
import { facilityId } from './_ids';

// TODO(backend): GET /api/v1/facilities
export const facilities: Facility[] = [
  // ─── GURUGRAM, Haryana ───────────────────────────────────────────
  {
    id: facilityId(1),
    name: 'District Hospital Gurugram',
    tier: 'dh',
    district: 'Gurugram',
    taluka: 'Gurugram',
    pincode: '122001',
    latitude: 28.4595,
    longitude: 77.0266,
    departments: ['general_opd', 'maternal_child_health', 'paediatrics', 'obstetrics', 'general_surgery', 'dental', 'emergency'],
    verified: true,
  },
  {
    id: facilityId(2),
    name: 'Civil Hospital Sohna',
    tier: 'sdh',
    district: 'Gurugram',
    taluka: 'Sohna',
    pincode: '122103',
    latitude: 28.2435,
    longitude: 77.0679,
    departments: ['general_opd', 'maternal_child_health', 'paediatrics', 'obstetrics', 'general_surgery', 'dental', 'emergency'],
    verified: true,
  },
  {
    id: facilityId(3),
    name: 'Primary Health Centre, Pataudi',
    tier: 'phc',
    district: 'Gurugram',
    taluka: 'Pataudi',
    pincode: '122503',
    latitude: 28.3210,
    longitude: 76.8180,
    departments: ['general_opd', 'maternal_child_health'],
    verified: false,
  },
  {
    id: facilityId(4),
    name: 'Community Health Centre, Farrukhnagar',
    tier: 'chc',
    district: 'Gurugram',
    taluka: 'Farrukhnagar',
    pincode: '122506',
    latitude: 28.4560,
    longitude: 76.8432,
    departments: ['general_opd', 'maternal_child_health', 'paediatrics', 'obstetrics', 'general_surgery', 'dental'],
    verified: false,
  },
  {
    id: facilityId(5),
    name: 'Primary Health Centre, Wazirabad',
    tier: 'phc',
    district: 'Gurugram',
    taluka: 'Gurugram',
    pincode: '122001',
    latitude: 28.4931,
    longitude: 77.0145,
    departments: ['general_opd', 'maternal_child_health'],
    verified: false,
  },

  // ─── FARIDABAD, Haryana ───────────────────────────────────────────
  {
    id: facilityId(6),
    name: 'B.K. Hospital Faridabad',
    tier: 'dh',
    district: 'Faridabad',
    taluka: 'Faridabad',
    pincode: '121001',
    latitude: 28.4089,
    longitude: 77.3178,
    departments: ['general_opd', 'maternal_child_health', 'paediatrics', 'obstetrics', 'general_surgery', 'dental', 'emergency'],
    verified: true,
  },
  {
    id: facilityId(7),
    name: 'Community Health Centre, Ballabhgarh',
    tier: 'chc',
    district: 'Faridabad',
    taluka: 'Ballabhgarh',
    pincode: '121004',
    latitude: 28.3417,
    longitude: 77.3201,
    departments: ['general_opd', 'maternal_child_health', 'paediatrics', 'obstetrics', 'general_surgery', 'dental'],
    verified: true,
  },
  {
    id: facilityId(8),
    name: 'Primary Health Centre, Tigaon',
    tier: 'phc',
    district: 'Faridabad',
    taluka: 'Tigaon',
    pincode: '121101',
    latitude: 28.3780,
    longitude: 77.4100,
    departments: ['general_opd', 'maternal_child_health'],
    verified: false,
  },

  // ─── GHAZIABAD, Uttar Pradesh ──────────────────────────────────────
  {
    id: facilityId(9),
    name: 'District Combined Hospital Ghaziabad',
    tier: 'dh',
    district: 'Ghaziabad',
    taluka: 'Ghaziabad',
    pincode: '201001',
    latitude: 28.6692,
    longitude: 77.4538,
    departments: ['general_opd', 'maternal_child_health', 'paediatrics', 'obstetrics', 'general_surgery', 'dental', 'emergency'],
    verified: true,
  },
  {
    id: facilityId(10),
    name: 'Community Health Centre, Modinagar',
    tier: 'chc',
    district: 'Ghaziabad',
    taluka: 'Modinagar',
    pincode: '201204',
    latitude: 28.8362,
    longitude: 77.5779,
    departments: ['general_opd', 'maternal_child_health', 'paediatrics', 'obstetrics', 'general_surgery', 'dental'],
    verified: true,
  },
  {
    id: facilityId(11),
    name: 'Primary Health Centre, Loni',
    tier: 'phc',
    district: 'Ghaziabad',
    taluka: 'Loni',
    pincode: '201102',
    latitude: 28.7468,
    longitude: 77.2891,
    departments: ['general_opd', 'maternal_child_health'],
    verified: false,
  },
  {
    id: facilityId(12),
    name: 'Primary Health Centre, Muradnagar',
    tier: 'phc',
    district: 'Ghaziabad',
    taluka: 'Muradnagar',
    pincode: '201206',
    latitude: 28.7775,
    longitude: 77.5041,
    departments: ['general_opd', 'maternal_child_health'],
    verified: false,
  },

  // ─── GAUTAM BUDDHA NAGAR (NOIDA), Uttar Pradesh ──────────────────
  {
    id: facilityId(13),
    name: 'District Hospital Gautam Buddha Nagar',
    tier: 'dh',
    district: 'Gautam Buddha Nagar',
    taluka: 'Noida',
    pincode: '201301',
    latitude: 28.5355,
    longitude: 77.3910,
    departments: ['general_opd', 'maternal_child_health', 'paediatrics', 'obstetrics', 'general_surgery', 'dental', 'emergency'],
    verified: true,
  },
  {
    id: facilityId(14),
    name: 'Community Health Centre, Dadri',
    tier: 'chc',
    district: 'Gautam Buddha Nagar',
    taluka: 'Dadri',
    pincode: '203207',
    latitude: 28.5543,
    longitude: 77.5588,
    departments: ['general_opd', 'maternal_child_health', 'paediatrics', 'obstetrics', 'general_surgery', 'dental'],
    verified: true,
  },
  {
    id: facilityId(15),
    name: 'Primary Health Centre, Jewar',
    tier: 'phc',
    district: 'Gautam Buddha Nagar',
    taluka: 'Jewar',
    pincode: '203135',
    latitude: 28.1249,
    longitude: 77.5465,
    departments: ['general_opd', 'maternal_child_health'],
    verified: false,
  },

  // ─── MEERUT, Uttar Pradesh ────────────────────────────────────────
  {
    id: facilityId(16),
    name: 'L.L.R.M. Medical College Hospital Meerut',
    tier: 'dh',
    district: 'Meerut',
    taluka: 'Meerut',
    pincode: '250004',
    latitude: 28.9845,
    longitude: 77.7064,
    departments: ['general_opd', 'maternal_child_health', 'paediatrics', 'obstetrics', 'general_surgery', 'dental', 'emergency'],
    verified: true,
  },
  {
    id: facilityId(17),
    name: 'Community Health Centre, Hapur',
    tier: 'chc',
    district: 'Meerut',
    taluka: 'Hapur',
    pincode: '245101',
    latitude: 28.7303,
    longitude: 77.7796,
    departments: ['general_opd', 'maternal_child_health', 'paediatrics', 'obstetrics', 'general_surgery', 'dental'],
    verified: true,
  },
  {
    id: facilityId(18),
    name: 'Primary Health Centre, Sardhana',
    tier: 'phc',
    district: 'Meerut',
    taluka: 'Sardhana',
    pincode: '250342',
    latitude: 29.1442,
    longitude: 77.6165,
    departments: ['general_opd', 'maternal_child_health'],
    verified: false,
  },
  {
    id: facilityId(19),
    name: 'Primary Health Centre, Kharkhoda',
    tier: 'phc',
    district: 'Meerut',
    taluka: 'Kharkhoda',
    pincode: '250404',
    latitude: 28.8714,
    longitude: 77.0349,
    departments: ['general_opd', 'maternal_child_health'],
    verified: false,
  },

  // ─── SONIPAT, Haryana ─────────────────────────────────────────────
  {
    id: facilityId(20),
    name: 'General Hospital Sonipat',
    tier: 'dh',
    district: 'Sonipat',
    taluka: 'Sonipat',
    pincode: '131001',
    latitude: 28.9931,
    longitude: 77.0151,
    departments: ['general_opd', 'maternal_child_health', 'paediatrics', 'obstetrics', 'general_surgery', 'dental', 'emergency'],
    verified: true,
  },
  {
    id: facilityId(21),
    name: 'Community Health Centre, Gohana',
    tier: 'chc',
    district: 'Sonipat',
    taluka: 'Gohana',
    pincode: '131301',
    latitude: 29.1407,
    longitude: 76.7008,
    departments: ['general_opd', 'maternal_child_health', 'paediatrics', 'obstetrics', 'general_surgery', 'dental'],
    verified: true,
  },
  {
    id: facilityId(22),
    name: 'Primary Health Centre, Kharkhoda',
    tier: 'phc',
    district: 'Sonipat',
    taluka: 'Kharkhoda',
    pincode: '131403',
    latitude: 28.8650,
    longitude: 77.0472,
    departments: ['general_opd', 'maternal_child_health'],
    verified: false,
  },
  {
    id: facilityId(23),
    name: 'Health & Wellness Sub-Centre, Kundli',
    tier: 'sub_centre',
    district: 'Sonipat',
    taluka: 'Sonipat',
    pincode: '131028',
    latitude: 28.8730,
    longitude: 77.0420,
    departments: ['general_opd', 'maternal_child_health'],
    verified: false,
  },
];

/** Lookup a facility by ID */
export function getFacility(id: string): Facility | undefined {
  return facilities.find(f => f.id === id);
}
