import type { SymptomId } from '../types';

export const EN_LEXICON: Record<SymptomId, readonly string[]> = {
  // Cardiovascular & Thoracic
  chest_pain: [
    'chest pain',
    'pain in chest',
    'chest ache',
    'chest tightness',
    'pressure in chest',
    'chest discomfort',
    'heavy chest',
  ],
  chest_pain_radiating: [
    'chest feels heavy and my left arm is numb',
    'my chest feels heavy and my left arm is numb',
    'left arm is numb with pain spreading',
    'chest pain spreading to arm',
    'chest pain radiating to left arm',
    'chest pain spreading to jaw',
    'pain in chest and neck',
    'pain radiating to shoulder',
    'chest pain shooting to back',
    'pain spreading to jaw',
  ],
  chest_pain_with_sweating: [
    'chest pain with sweating',
    'chest pain and cold sweats',
    'sweating with chest tightness',
    'cold sweat and chest pressure',
    'perspiring with chest ache',
  ],
  palpitations: [
    'palpitations',
    'racing heart',
    'heart beating fast',
    'fluttering in chest',
    'irregular heartbeat',
    'pounding heart',
  ],
  swelling_both_legs: [
    'swelling in both legs',
    'swollen feet and ankles',
    'swelling of feet',
    'puffy legs',
    'fluid in both feet',
  ],

  // Respiratory
  breathless: [
    'breathless',
    'shortness of breath',
    'difficulty breathing',
    'hard to breathe',
    'trouble catching breath',
    'feeling winded',
  ],
  severe_breathlessness: [
    'severe breathlessness',
    'gasping for air',
    'cannot breathe',
    'unable to breathe lying down',
    'struggling for every breath',
    'choking sensation',
    'very breathless',
    'very breathless while sitting',
  ],
  stridor: [
    'stridor',
    'crowing sound breathing in',
    'high pitched whistling while inhaling',
    'noisy harsh breathing',
    'whistling when breathing in',
  ],
  cough: [
    'cough',
    'coughing',
    'persistent cough',
    'dry cough',
    'phlegm cough',
    'hacking cough',
  ],
  cough_blood: [
    'coughing up dark blood',
    'coughing up blood',
    'coughing blood',
    'cough with blood',
    'spitting blood',
    'blood in sputum',
    'bloody phlegm',
  ],
  wheezing: [
    'wheezing',
    'whistling chest',
    'musical chest sounds',
    'whistling breath exhaling',
    'rattling wheeze',
  ],

  // Neurological & Mental State
  sudden_weakness_one_side: [
    'cannot lift his right arm',
    'cannot lift arm',
    'sudden weakness on one side',
    'one sided paralysis',
    'numbness on left side',
    'numbness on right side',
    'arm and leg unable to move',
    'weakness in right arm and leg',
    'loss of power in left limbs',
  ],
  slurred_speech: [
    'speech is completely tangled and slurred',
    'speech is slurred',
    'slurred speech',
    'difficulty speaking clearly',
    'words tangled up',
    'unable to form words',
    'speech slurring suddenly',
  ],
  facial_droop: [
    'facial droop',
    'drooping face on one side',
    'mouth crooked to one side',
    'uneven smile',
    'face twisted',
  ],
  severe_headache: [
    'severe headache',
    'worst headache of life',
    'thunderclap head pain',
    'terrible pounding headache',
    'unbearable pain in head',
  ],
  fits: [
    'fits',
    'seizure',
    'convulsions',
    'shaking uncontrollably',
    'epileptic attack',
    'body stiffening and jerking',
  ],
  unconscious: [
    'unconscious',
    'passed out completely',
    'blacked out not waking',
    'unable to wake up',
    'unresponsive',
  ],
  confusion: [
    'confusion',
    'disoriented',
    'talking nonsense',
    'does not recognize family',
    'acute mental confusion',
  ],
  dizziness: [
    'dizziness',
    'feeling faint',
    'room is spinning',
    'vertigo',
    'lightheadedness',
  ],
  fainting: [
    'fainting',
    'syncope',
    'fell down unconscious briefly',
    'sudden collapse and recovered',
  ],
  suicidal_intent: [
    'suicidal intent',
    'want to end life',
    'thinking of suicide',
    'want to kill myself',
    'thoughts of harming self',
  ],

  // Trauma, Envenomation & Haemorrhage
  heavy_bleeding: [
    'heavy bleeding',
    'uncontrolled bleeding',
    'gushing blood',
    'bleeding heavily from wound',
    'continuous blood loss',
  ],
  wound_deep: [
    'deep cut',
    'deep open wound',
    'gaping flesh laceration',
    'wound needing stitches',
    'knife cut',
  ],
  burn: [
    'burn',
    'scald injury',
    'hot oil burn',
    'hot water burn',
    'minor skin burn',
  ],
  severe_burn: [
    'severe burn',
    'charred skin burn',
    'large blistering burn',
    'flame burn across face or chest',
    'extensive electrical burn',
  ],
  fracture_suspected: [
    'suspected fracture',
    'broken bone',
    'deformed broken arm',
    'crooked leg unable to step',
    'bone snapped',
  ],
  major_trauma: [
    'major trauma',
    'severe road accident',
    'fell from height',
    'crushed by vehicle',
    'hit by tractor',
  ],
  snakebite: [
    'snakebite',
    'bitten by snake',
    'snake fangs bite mark',
    'saw snake bite leg',
    'serpent bite',
  ],
  scorpion_sting: [
    'scorpion sting',
    'bitten by scorpion',
    'scorpion venom sting',
    'stung by scorpion',
  ],
  poisoning: [
    'poisoning',
    'swallowed poison',
    'drank insecticide',
    'pesticide ingestion',
    'consumed rat poison',
    'chemical ingestion',
  ],

  // Gastrointestinal & Abdominal
  abdominal_pain: [
    'abdominal pain',
    'stomach pain',
    'tummy ache',
    'cramps in belly',
    'pain in abdomen',
  ],
  severe_abdominal_pain: [
    'severe abdominal pain',
    'excruciating stomach agony',
    'board like rigid belly',
    'unbearable belly agony',
    'acute sudden abdominal pain',
  ],
  vomiting: [
    'vomiting',
    'throwing up',
    'emesis',
    'nausea and vomiting',
    'repeated vomiting',
  ],
  vomiting_blood: [
    'vomiting blood',
    'throwing up blood',
    'coffee ground vomit',
    'blood in vomit',
    'red blood vomiting',
  ],
  diarrhoea: [
    'diarrhoea',
    'loose motions',
    'watery stool',
    'frequent loose stool',
    'runny tummy',
  ],
  blood_in_stool: [
    'blood in stool',
    'red blood in motions',
    'black tarry stool',
    'bloody motions',
    'passing dark blood from rectum',
  ],
  severe_dehydration_signs: [
    'severe dehydration signs',
    'sunken eyes and extreme thirst',
    'dry tongue not passing urine',
    'lethargic dehydrated with dry mouth',
  ],
  heartburn: [
    'heartburn',
    'acid reflux',
    'burning sensation in chest after eating',
    'acidity',
    'sour burps',
  ],
  constipation: [
    'constipation',
    'unable to pass stool for days',
    'hard dry stool',
    'difficulty passing stool',
  ],

  // Genitourinary
  cant_pass_urine: [
    'cant pass urine',
    'unable to pass urine',
    'stopped passing water',
    'urinary retention',
    'no urine coming out',
  ],
  pain_urination: [
    'pain while urinating',
    'burning sensation passing urine',
    'hurts to pee',
    'painful urination',
  ],
  blood_in_urine: [
    'blood in urine',
    'red coloured urine',
    'cola urine',
    'passing bloody urine',
  ],
  scrotal_pain_sudden: [
    'sudden severe testicle pain',
    'severe testicle pain started',
    'sudden scrotal pain',
    'severe testicle pain',
    'swollen painful testicle',
    'acute groin testicle pain',
  ],

  // Obstetric & Gynaecological
  pregnancy_bleeding: [
    'bleeding in pregnancy',
    'vaginal bleeding while pregnant',
    'spotting blood during pregnancy',
    'pregnant and bleeding',
  ],
  pregnancy_convulsion: [
    'pregnancy convulsion',
    'fits during pregnancy',
    'seizure while pregnant',
    'shaking fits after delivery',
  ],
  pregnancy_severe_headache_vision: [
    'severe headache with vision blur in pregnancy',
    'headache and blurry vision while pregnant',
    'pounding head with spots in eyes pregnant',
    'high pressure headache in pregnancy',
  ],
  reduced_fetal_movement: [
    'reduced fetal movement',
    'baby not moving in womb',
    'decreased baby kicks',
    'unborn baby stopped moving',
  ],
  rupture_of_membranes: [
    'water broke',
    'fluid leaking from vagina',
    'gush of watery fluid pregnant',
    'rupture of membranes',
  ],
  labour_pain: [
    'labour pain',
    'pregnancy contractions',
    'regular labor pains',
    'tightening pains in abdomen pregnant',
  ],
  postpartum_bleeding: [
    'postpartum bleeding',
    'heavy bleeding after delivery',
    'soaking pads after childbirth',
    'flooding blood after baby born',
  ],
  foul_vaginal_discharge: [
    'foul vaginal discharge',
    'smelly vaginal discharge',
    'bad smelling discharge with fever',
    'purulent vaginal discharge',
  ],

  // Paediatric & Neonatal Danger Signs
  infant_not_feeding: [
    'baby not feeding',
    'infant refusing to suckle',
    'baby unable to drink milk',
    'newborn stopped feeding',
  ],
  infant_lethargy: [
    'infant lethargy',
    'baby unusually floppy',
    'infant hard to wake up',
    'newborn completely limp',
  ],
  infant_fast_breathing: [
    'infant fast breathing',
    'baby breathing very fast',
    'rapid breathing in baby',
    'newborn panting quickly',
  ],
  chest_indrawing: [
    'chest indrawing',
    'lower chest pulls in breathing',
    'child chest sucking in',
    'deep chest retractions child',
  ],
  infant_fever: [
    'fever in newborn',
    'infant fever under two months',
    'baby hot to touch under 2 months',
    'fever in baby under sixty days',
  ],
  infant_hypothermia: [
    'baby abnormally cold to touch',
    'infant hypothermia',
    'newborn feels cold and shivering',
    'low body temperature in infant',
  ],
  child_fever: [
    'child fever',
    'fever in child',
    'child hot with fever',
    'toddler fever',
  ],
  child_ear_pain: [
    'child pulling ear in pain',
    'ear pain in child',
    'child crying with ear ache',
    'pus draining from child ear',
  ],

  // Systemic, Cutaneous & Sensory
  high_fever: [
    'high fever',
    'burning fever with chills',
    'shivering fever',
    'high temperature with rigors',
  ],
  fever_with_stiff_neck: [
    'fever with stiff neck',
    'high fever unable to bend neck',
    'fever and neck rigidity',
    'fever with chin to chest pain',
  ],
  fever_with_petechial_rash: [
    'fever with petechial rash',
    'fever with purple spots on skin',
    'fever with dark non blanching spots',
    'fever with reddish purple rash',
  ],
  severe_allergic_reaction: [
    'severe allergic reaction',
    'swollen face lips and tongue with wheeze',
    'anaphylaxis swollen throat',
    'allergic reaction with breathing difficulty',
  ],
  body_ache: [
    'body ache',
    'generalized muscle aches',
    'whole body pain',
    'sore limbs and back',
  ],
  weakness_fatigue: [
    'weakness and fatigue',
    'extreme exhaustion',
    'feeling completely drained',
    'too weak to stand',
  ],
  skin_rash: [
    'skin rash',
    'itchy red rash',
    'spots on skin without fever',
    'pruritic eruption',
  ],
  joint_pain: [
    'joint pain',
    'knee pain',
    'swollen painful knee',
    'pain in multiple joints',
  ],
  eye_injury: [
    'eye injury',
    'foreign object in eye',
    'chemical splash in eye',
    'sharp trauma to eye',
  ],
  eye_redness_pain: [
    'painful red eye',
    'eye discharge and redness',
    'gritty burning eye',
    'pink eye with pain',
  ],
  ear_discharge: [
    'ear discharge',
    'pus leaking from ear',
    'fluid coming out of ear',
    'smelly drainage from ear',
  ],
  sore_throat: [
    'sore throat',
    'pain swallowing food',
    'scratchy raw throat',
    'throat irritation',
  ],
};
