import type { SymptomId } from '../types';

export const HI_LEXICON: Record<SymptomId, readonly string[]> = {
  // Cardiovascular & Thoracic
  chest_pain: [
    'सीने में दर्द हो रहा है',
    'छाती में दर्द है',
    'छाती भारी लग रही है',
    'सीने में भारीपन',
    'छाती में खिंचाव',
    'chest me dard ho raha hai',
    'chhati me dard',
    'seene me dard',
    'chhati bhari lag rahi hai',
  ],
  chest_pain_radiating: [
    'सीने का दर्द बाएं हाथ में जा रहा है',
    'छाती का दर्द जबड़े तक फैल रहा है',
    'सीने से कंधे तक तेज दर्द',
    'seene ka dard bayen hath me',
    'chhati ka dard gale me fail raha hai',
  ],
  chest_pain_with_sweating: [
    'सीने में दर्द हो रहा है और ठंडा पसीना आ रहा है',
    'सीने में दर्द के साथ ठंडा पसीना',
    'छाती में भारीपन और पसीना आ रहा है',
    'सीने में तेज दर्द पसीना छूट रहा है',
    'chhati me dard aur paseena',
    'seene me dard thanda paseena',
    'chest me heavy pain ahe ani bohot paseena aa raha hai',
    'chest me heavy pain',
    'bohot paseena aa raha hai',
  ],
  palpitations: [
    'दिल तेजी से धड़क रहा है',
    'दिल की धड़कन तेज होना',
    'छाती में धक धक होना',
    'dil tezi se dhadak raha hai',
    'dhadkan aniyamit hona',
    'dil ghabrana',
  ],
  swelling_both_legs: [
    'दोनों पैरों में सूजन',
    'पैरों और पंजों में भारी सूजन',
    'पैरों में पानी भरना',
    'dono pairo me sujan',
    'pairo me sujan',
  ],

  // Respiratory
  breathless: [
    'साँस नहीं आ रही',
    'साँस फूल रही है',
    'साँस लेने में तकलीफ हो रही है',
    'दम फूलना',
    'saans phool rahi hai',
    'saans nahi aa rahi',
    'saans lene me takleef',
    'dam ghutna',
  ],
  severe_breathlessness: [
    'बहुत ज्यादा साँस फूलना',
    'साँस के लिए तड़पना',
    'बोल भी नहीं पा रहे साँस के कारण',
    'bahut jyada saans phoolna',
    'saans rukti lagna',
  ],
  stridor: [
    'साँस लेते समय सीटी जैसी तीखी आवाज',
    'गले से घुर्र घुर्र सीटी की आवाज',
    'saans lete waqt seeti jaisi aawaz',
    'stridor gale se awaz',
  ],
  cough: [
    'खाँसी आ रही है',
    'सूखी खाँसी',
    'बलगम वाली खाँसी',
    'लगातार खाँसी',
    'khasi aa rahi hai',
    'sukhi khasi',
    'balgam wali khansi',
  ],
  cough_blood: [
    'खाँसी में खून आना',
    'बलगम में लाल खून गिरना',
    'खाँसते हुए खून निकलना',
    'khasi me khoon aana',
    'balgam me khoon',
  ],
  wheezing: [
    'छाती से सीटी की आवाज आना',
    'घरघराहट होना',
    'साँस छोड़ते वक्त सीटी',
    'chhati se seeti ki awaz',
    'ghargharhat hona',
  ],

  // Neurological & Mental State
  sudden_weakness_one_side: [
    'अचानक एक तरफ का हाथ पैर कमजोर पड़ना',
    'शरीर का बायाँ हिस्सा सुन्न हो गया',
    'दायाँ हाथ पैर काम नहीं कर रहा',
    'ek taraf ka hissa sunn hona',
    'hath pair kamjor padna achanak',
    'lakwa marna',
  ],
  slurred_speech: [
    'बोली लड़खड़ाना',
    'आवाज साफ नहीं निकल रही',
    'अचानक जुबान लथपथ होना',
    'boli ladkhadana',
    'awaz saaf nahi nikalna',
    'juban ladkhadana',
  ],
  facial_droop: [
    'मुँह एक तरफ टेढ़ा हो गया',
    'चेहरा लटकना',
    'मुँह का कोना झुक जाना',
    'muh tedha hona',
    'chehra latak jana',
  ],
  severe_headache: [
    'असहनीय सिरदर्द',
    'सिर फटने जैसा भयानक दर्द',
    'जिंदगी का सबसे भयानक सिरदर्द',
    'sir fatne jaisa dard',
    'bahut tez sirdard',
  ],
  fits: [
    'दौरा पड़ा',
    'झटके आ रहे हैं',
    'मिरगी का दौरा',
    'हाथ पैर अकड़कर काँपना',
    'daura pada',
    'jhatke aa rahe hain',
    'mirgi aana',
    'body akadna aur kaampna',
  ],
  unconscious: [
    'बेहोश हो गए',
    'अचेत पड़ा है कोई होश नहीं',
    'होश खो बैठना',
    'behoshi aana',
    'behtar behosh pada hai',
  ],
  confusion: [
    'भ्रमित होना कुछ समझ नहीं आ रहा',
    'उल्टी सीधी बातें करना',
    'घरवालों को पहचान नहीं पा रहे',
    'bhramit hona behki baatein',
    'pehechan nahi pana',
  ],
  dizziness: [
    'चक्कर आ रहे हैं',
    'सिर घूम रहा है',
    'आँखों के आगे अँधेरा छाना',
    'chakkar aana',
    'sir ghoomna',
  ],
  fainting: [
    'चक्कर खाकर गिर पड़े',
    'अचानक गश खाकर गिरना और उठना',
    'chakkar khakar behosh girna',
    'gash khana',
  ],
  suicidal_intent: [
    'जान देने का मन कर रहा है',
    'आत्महत्या के विचार आना',
    'खुद को नुकसान पहुँचाने की सोच',
    'jaan dene ka man',
    'aatmahatya ki soch',
  ],

  // Trauma, Envenomation & Haemorrhage
  heavy_bleeding: [
    'बहुत ज्यादा खून बह रहा है',
    'खून का फव्वारा फूटना',
    'घाव से लगातार भारी रक्तस्राव',
    'bahut jyada khoon behna',
    'khoon band nahi ho raha',
  ],
  wound_deep: [
    'गहरा घाव',
    'कट लग जाना मांस दिखना',
    'टांके लगने वाला गहरा कट',
    'gehra ghaav',
    'tanke lagne wala cut',
  ],
  burn: [
    'जल गया है',
    'गर्म तेल या पानी से जलना',
    'हल्की जलन और फफोला',
    'jal gaya hai',
    'garm tel se jalna',
  ],
  severe_burn: [
    'बहुत बुरी तरह जलना',
    'आग में झुलस जाना',
    'चेहरा और छाती जलना',
    'bahut buri tarah jalna',
    'aag me jhulsa',
  ],
  fracture_suspected: [
    'हड्डी टूट गई लगती है',
    'हाथ पैर टेढ़ा हो जाना',
    'हड्डी चटकने की आवाज आना',
    'haddi toot gayi lagti hai',
    'pair tedha hona',
  ],
  major_trauma: [
    'बड़ा एक्सीडेंट हो गया',
    'गाड़ी से कुचला जाना',
    'ऊंचाई से गिरना',
    'bada accident ho gaya',
    'unchai se girna',
  ],
  snakebite: [
    'साँप ने काट लिया',
    'सर्पदंश होना',
    'साँप के दाँत के दो निशान',
    'saanp ne kaat liya',
    'sarpdansh',
    'saanp ka kata',
  ],
  scorpion_sting: [
    'बिच्छू ने डंक मारा',
    'बिच्छू का डंक बहुत तेज दर्द',
    'bichhu ne dank mara',
    'bichhu ka katna',
  ],
  poisoning: [
    'जहर पी लिया',
    'कीटनाशक दवा निगल ली',
    'चूहे मारने की दवा खाना',
    'khet ki kida marne wali dava pi li',
    'zahar pee liya',
    'poisoning ho gaya',
  ],

  // Gastrointestinal & Abdominal
  abdominal_pain: [
    'पेट में दर्द हो रहा है',
    'पेट में मरोड़ उठना',
    'पेट में ऐंठन और दर्द',
    'pet me dard ho raha hai',
    'pet me marod',
  ],
  severe_abdominal_pain: [
    'पेट में असहनीय भयानक दर्द',
    'पेट पत्थर जैसा कड़ा हो गया',
    'अचानक पेट का तेज दर्द',
    'pet me asahniya dard',
    'pet pathar jaisa katha',
  ],
  vomiting: [
    'उल्टी हो रही है',
    'बार बार उल्टी आना',
    'कै होना',
    'ulti ho rahi hai',
    'bar bar ulti',
  ],
  vomiting_blood: [
    'उल्टी में खून गिरना',
    'खून की उल्टी होना',
    'काले खून की कै',
    'khoon ki ulti hona',
    'ulti me khoon nikalna',
  ],
  diarrhoea: [
    'पतले दस्त लगना',
    'पानी जैसे पतले मोशन',
    'बार बार दस्त होना',
    'patle dast lagna',
    'loose motion hona',
  ],
  blood_in_stool: [
    'लैट्रिन में खून आना',
    'दस्त में लाल खून गिरना',
    'काला कोलतार जैसा मल आना',
    'latrine me khoon aana',
    'dast me khoon',
  ],
  severe_dehydration_signs: [
    'आँखें अंदर धंस जाना बहुत प्यास',
    'शरीर में पानी की भारी कमी',
    'पेशाब बंद और मुँह सूखना',
    'aankhein andar dhasna sukha gala',
    'dehydration bohot jyada',
  ],
  heartburn: [
    'छाती में जलन होना',
    'खट्टी डकारें आना',
    'गैस और सीने में तेजाब लगना',
    'chhati me jalan',
    'khatti dakar',
    'acidity hona',
  ],
  constipation: [
    'कब्ज होना कई दिनों से शौच न होना',
    'मल त्याग में भारी परेशानी',
    'kabz hona latrine na aana',
    'constipation pet saaf na hona',
  ],

  // Genitourinary
  cant_pass_urine: [
    'पेशाब नहीं हो रहा',
    'पेशाब आना बंद हो गया है',
    'पेशाब रुक जाना तड़प होना',
    'peshab nahi ho raha',
    'peshab ruk jana',
    'peshab band ho gaya hai',
  ],
  pain_urination: [
    'पेशाब में तेज जलन',
    'पेशाब करते समय दर्द',
    'peshab me jalan hona',
    'peshab me dard',
  ],
  blood_in_urine: [
    'पेशाब में खून आना',
    'लाल रंग का पेशाब निकलना',
    'peshab me khoon aana',
    'laal peshab aana',
  ],
  scrotal_pain_sudden: [
    'अंडकोष में अचानक भयानक दर्द',
    'गोटे में तेज दर्द और सूजन',
    'andkosh me tez dard',
    'testicle me dard',
  ],

  // Obstetric & Gynaecological
  pregnancy_bleeding: [
    'प्रेगनेंसी में खून आ रहा है',
    'गर्भावस्था में रक्तस्राव हो रहा है',
    'गर्भवती होने पर खून के धब्बे',
    'pregnancy me khoon aa raha hai',
    'garbh me bleeding hona',
  ],
  pregnancy_convulsion: [
    'गर्भवती को दौरे पड़ना',
    'प्रेगनेंसी में झटके आना',
    'डिलिवरी के बाद तेज झटके',
    'pregnancy me daura padna',
    'delivery ke baad jhatke',
  ],
  pregnancy_severe_headache_vision: [
    'गर्भावस्था में सिरदर्द और धुंधला दिखना',
    'प्रेगनेंसी में आँखों के आगे अंधेरा और सिरदर्द',
    'pregnancy me sirdard aur dhundhla',
    'गर्भावस्था में सिर में तेज दर्द और चक्कर',
  ],
  reduced_fetal_movement: [
    'पेट में बच्चा हिल नहीं रहा',
    'गर्भ में बच्चे की हलचल कम होना',
    'बच्चे की लात महसूस नहीं हो रही',
    'pet me baccha hil nahi raha',
    'bacche ki halchal band',
  ],
  rupture_of_membranes: [
    'पानी की थैली फट जाना',
    'योनि से अचानक पानी छूटना',
    'pani ki thaili fatna',
    'yoni se paani behna',
  ],
  labour_pain: [
    'प्रसव पीड़ा शुरू होना',
    'डिलिवरी का दर्द उठना',
    'कमर और पेट में नियमित दर्द',
    'delivery ka dard prasav peeda',
    'labour pain shuru hona',
  ],
  postpartum_bleeding: [
    'प्रसव के बाद भारी ब्लीडिंग',
    'डिलिवरी के बाद बहुत ज्यादा खून बहना',
    'delivery ke baad bohot khoon behna',
    'prasav ke baad bleeding',
  ],
  foul_vaginal_discharge: [
    'योनि से बदबूदार स्राव आना',
    'खराब गंध वाला पानी गिरना',
    'badbudaar discharge aana',
    'yoni se gandh aana',
  ],

  // Paediatric & Neonatal Danger Signs
  infant_not_feeding: [
    'बच्चा दूध नहीं पी रहा',
    'बच्चा स्तनपान नहीं कर रहा',
    'नवजात शिशु दूध छोड़ चुका है',
    'baccha doodh nahi pee raha',
    'baccha stanpan nahi kar raha',
  ],
  infant_lethargy: [
    'नवजात बच्चा एकदम सुस्त पड़ा है',
    'शिशु जगाने पर भी नहीं जाग रहा',
    'बच्चा ढीला पड़ गया है',
    'baccha sust pada hai jagta nahi',
    'infant dheela padna',
  ],
  infant_fast_breathing: [
    'बच्चा बहुत तेज तेज साँस ले रहा है',
    'शिशु की साँस धौंकनी जैसी तेज चलना',
    'baccha tezi se saans le raha hai',
    'infant fast breathing',
  ],
  chest_indrawing: [
    'साँस लेते समय बच्चे की पसली अंदर धंसना',
    'बच्चे की छाती नीचे धंस रही है',
    'bacche ki pasli dhasna',
    'chhati andar khinchna',
  ],
  infant_fever: [
    'दो महीने से छोटे बच्चे को तेज बुखार',
    'नवजात का शरीर तवे जैसा गर्म',
    'chote bacche ko bukhar',
    'navjat ko tez bukhar',
  ],
  infant_hypothermia: [
    'नवजात शिशु का शरीर ठंडा पड़ जाना',
    'बच्चा छूने में एकदम ठंडा लगना',
    'baccha thanda pad jana',
    'infant body cold hona',
  ],
  child_fever: [
    'बच्चे को बुखार है',
    'बच्चे का बदन तप रहा है',
    'bacche ko bukhar hai',
    'child fever bukhar',
  ],
  child_ear_pain: [
    'बच्चा कान पकड़कर रो रहा है',
    'बच्चे के कान में तेज दर्द',
    'baccha kaan pakadkar rona',
    'bacche ke kaan me dard',
  ],

  // Systemic, Cutaneous & Sensory
  high_fever: [
    'तेज बुखार चढ़ना',
    'कपकपी के साथ तेज बुखार',
    'बदन तपना और ठंड लगना',
    'tez bukhar aana',
    'kapkapi ke sath bukhar',
  ],
  fever_with_stiff_neck: [
    'बुखार के साथ गर्दन अकड़ जाना',
    'बुखार में गर्दन झुकाने में दर्द',
    'bukhar ke sath gardan akadna',
    'bukhar gardan me akdan',
  ],
  fever_with_petechial_rash: [
    'बुखार के साथ शरीर पर लाल जामुनी चकत्ते',
    'बुखार में त्वचा पर गहरे धब्बे निकलना',
    'bukhar ke sath laal chakatte',
    'तेज बुखार और त्वचा पर लाल धब्बे',
    'bukhar me lal chakatte padna',
  ],
  severe_allergic_reaction: [
    'चेहरा होंठ सूजना और साँस फूलना',
    'दवा या काटने से अचानक पूरा मुँह सूजना',
    'chehra honth sujna saans phoolna',
    'allergic reaction muh phoolna',
  ],
  body_ache: [
    'पूरे बदन में दर्द',
    'हाथ पैर टूट रहे हैं',
    'मांसपेशियों में दर्द',
    'pure badan me dard',
    'hath pair tootna',
  ],
  weakness_fatigue: [
    'बहुत ज्यादा कमजोरी और थकान',
    'उठने की भी ताकत न होना',
    'bahut jyada kamjori',
    'thakan aur kamjori',
  ],
  skin_rash: [
    'त्वचा पर खुजली वाले लाल दाने',
    'शरीर पर पित्ती या चकत्ते',
    'tvacha par daane khujli',
    'skin rash khujli hona',
  ],
  joint_pain: [
    'जोड़ों में दर्द',
    'घुटने में तेज दर्द और सूजन',
    'jodo me dard',
    'ghutne me dard sujan',
  ],
  eye_injury: [
    'आँख में चोट लग गई',
    'आँख में कुछ केमिकल या कंकड़ गिरना',
    'aankh me chot lagna',
    'aankh me kankad girna',
  ],
  eye_redness_pain: [
    'आँख लाल होना और कीचड़ आना',
    'आँख में तेज जलन और दर्द',
    'aankh laal hona dard',
    'aankh me jalan',
  ],
  ear_discharge: [
    'कान बह रहा है',
    'कान से पीब या मवाद निकलना',
    'kaan behna',
    'kaan se mavad nikalna',
  ],
  sore_throat: [
    'गले में दर्द और खराश',
    'निगलते समय गले में चुभन',
    'gale me kharash dard',
    'gale me chubhan',
  ],
};
