import type { SymptomId } from '../types';

export const MR_LEXICON: Record<SymptomId, readonly string[]> = {
  // Cardiovascular & Thoracic
  chest_pain: [
    'छातीत दुखतंय',
    'छातीत कळ येतेय',
    'छाती जड वाटतेय',
    'छातीत भरून आल्यासारखं वाटतंय',
    'छातीवर दाब वाटतोय',
    'chatit dukhtay',
    'chatit kal yetey',
    'chhati jad wattey',
    'chatit dab',
  ],
  chest_pain_radiating: [
    'छातीत जड वाटतेय आणि डावा हात खूप दुखतोय',
    'छातीत जड वाटतेय आणि डावा हात',
    'chatit kal yetey ani dava hat jad vattoy',
    'छातीतली कळ डाव्या हातात जातेय',
    'छातीतून जबड्याकडे दुखणे पसरतंय',
    'छाती आणि पाठीत तीव्र कळ',
    'chatitli kal davya hatat yetey',
    'chhati dukhoon jabdyat jane',
  ],
  chest_pain_with_sweating: [
    'छातीत दुखतंय आणि खूप गार घाम सुटलाय',
    'छातीत दुखतंय आणि खूप गार घाम',
    'छातीत दुखत असून गार घाम फुटलाय',
    'छातीत कळ आणि अंग गार पडून घाम',
    'छाती जड आणि खूप घाम सुटलाय',
    'chatit dukhtay ani gham yetoy',
    'chhati dukhoon thand gham sutne',
  ],
  palpitations: [
    'छातीत धडधडतंय',
    'काळजाची धडधड वाढलीय',
    'छातीत धकधक होणे',
    'chatit dhadhadtoy',
    'kaljat dhadhad hone',
  ],
  swelling_both_legs: [
    'दोन्ही पायांवर सूज आलीय',
    'पायाचे पंजे सुजले आहेत',
    'पायात पाणी साचल्यासारखी सूज',
    'donhi payanvar sooj aaliy',
    'pay sujne',
  ],

  // Respiratory
  breathless: [
    'दम लागतोय',
    'श्वास घ्यायला त्रास होतोय',
    'धाप लागतेय',
    'श्वास कोंडल्यासारखा वाटतोय',
    'dam lagtoy',
    'shwas ghyayla tras hotoy',
    'dhap lagtey',
    'shwas kondne',
  ],
  severe_breathlessness: [
    'खूप जास्त धाप लागतेय बोलता येत नाही',
    'श्वास गुदमरतोय प्राण चालल्यासारखा',
    'दम भयंकर लागणे',
    'shwas gudmartoy bolta yet nahi',
    'khup jast dhap lagne',
  ],
  stridor: [
    'श्वास घेताना घोगरा शिटीसारखा आवाज',
    'घशातून खरखर आवाज येणे',
    'shwas ghetana ghashatun shiti yetey',
    'stridor ghashatun aawaj',
  ],
  cough: [
    'खोकला येतोय',
    'कोरडा खोकला',
    'कफ पडणारा खोकला',
    'खोकल्याची उबळ येणे',
    'khokla yetoy',
    'korda khokla',
    'kaf khokla',
  ],
  cough_blood: [
    'खोकल्यातून रक्त पडतंय',
    'थुंकीत लाल रक्त येणे',
    'खोकून खोकून रक्त पडणे',
    'khoklyatun rakt padtay',
    'thunkit rakt yene',
  ],
  wheezing: [
    'छातीत शिटी वाजल्यासारखा आवाज',
    'छातीत घरघर वाजतेय',
    'chatit shiti wajtey',
    'chatit gharghar hone',
  ],

  // Neurological & Mental State
  sudden_weakness_one_side: [
    'एका बाजूचे अंग लुळे पडले',
    'डावा हात पाय अचानक बधिर झाला',
    'उजव्या अंगात त्राण उरला नाही',
    'eka bajuche ang lule padle',
    'dava hat pay kam karnyache band',
    'ek baju band padli',
  ],
  slurred_speech: [
    'जीभ जड झालीय बोलता येत नाही',
    'बोबडे बोलणे अचानक सुरू झाले',
    'तोंडातून शब्द फुटत नाहीत',
    'jeebh jad zali bolta yet nahi',
    'bobde bolne',
    'awaj adakhlatoy',
  ],
  facial_droop: [
    'तोंड एका बाजूला वाकडे झाले',
    'चेहरा एका बाजूला कलंडला',
    'tond vakde hone',
    'chehra eka bajula vadalela',
  ],
  severe_headache: [
    'डोके भयंकर दुखतंय डोके फुटल्यासारखे',
    'आयुष्यातील सर्वात भयंकर डोकेदुखी',
    'कपाळात तीव्र कळ मारणे',
    'doke bhayankar dukhtay',
    'doke futlyasarkhe dukhtey',
  ],
  fits: [
    'फिट आली',
    'झटके येतायत',
    'मिरगीचा झटका येणे',
    'हातपाय थरथर कापणे डोळे पांढरे करणे',
    'fit aali',
    'zhatke yetayt',
    'mirgicha zhatka',
    'dole pandhre hone hatpay kanpne',
  ],
  unconscious: [
    'शुद्ध हरपलीय अजिबात जागे होत नाहीत',
    'बेशुद्ध पडले आहेत',
    'shuddh harpali',
    'beshuddh padle ahet',
    'dole ughadt nahiyet',
  ],
  confusion: [
    'काही समजत नाहीये भलतंच बोलतायत',
    'घरच्यांना ओळखत नाहीत मती मंद झालीय',
    'kahi samjat nahiye bhaltech boltahet',
    'olakh dharat nahiyet',
  ],
  dizziness: [
    'चक्कर येतेय',
    'भोवळ येणे',
    'डोळ्यांसमोर अंधारी येणे',
    'chakkar yetey',
    'bhowal yene',
    'andhari yene',
  ],
  fainting: [
    'चक्कर येऊन धाडकन खाली पडले',
    'भोवळ येऊन पडणे आणि जागे होणे',
    'chakkar yeun khali padne',
    'sudden faint hone',
  ],
  suicidal_intent: [
    'जीव द्यावासा वाटतोय',
    'आत्महत्येचे विचार येत आहेत',
    'स्वतःला संपवून घेण्याची इच्छा',
    'jeev dyavasa wattoy',
    'aatmahatyeche vichar',
  ],

  // Trauma, Envenomation & Haemorrhage
  heavy_bleeding: [
    'खूप जास्त रक्त वाहून जातंय',
    'रक्ताची चिळकांडी उडतेय',
    'जखमेतून रक्त थांबतच नाहीये',
    'khup jast rakt vahun jatay',
    'rakt thambatch nahiye',
  ],
  wound_deep: [
    'खोल जखम झालीय',
    'मोठा घाव पडलाय टाके पडतील',
    'khol jakham zaliy',
    'motha ghav lagla',
  ],
  burn: [
    'भाजले आहे',
    'गरम पाण्याने किंवा तेलाने भाजणे',
    'त्वचेवर हलका फोड येणे',
    'bhajle ahe',
    'garm telani bhajne',
  ],
  severe_burn: [
    'खूप वाईट रीतीने भाजले',
    'आगीत होरपळून निघणे',
    'तोंड आणि छाती भाजून निघणे',
    'khup vait ritine bhajne',
    'aagit horpalne',
  ],
  fracture_suspected: [
    'हाड मोडल्यासारखे वाटतेय',
    'हात पाय वाकडा झालाय चालता येत नाही',
    'हाडातून कटकन आवाज येणे',
    'haad modlyasarkhe wattey',
    'pay vakda zala chalvat nahi',
  ],
  major_trauma: [
    'फार मोठा अपघात झाला',
    'गाडीने जोरदार धडक दिली',
    'उंचावरून खाली कोसळले',
    'motha apghat zala',
    'gadine dhadak dili unchavarun padne',
  ],
  snakebite: [
    'साप चावला',
    'सर्पदंश झाला',
    'सापाच्या दातांचे दोन व्रण उठले',
    'saap chavla',
    'sarpdansh zala',
    'sapan dasla',
  ],
  scorpion_sting: [
    'विंचू चावला',
    'विंचवाने नांगी मारली तीव्र ठसका',
    'vinchu chavla',
    'vinchavane danka marla',
  ],
  poisoning: [
    'विष प्यायले आहेत',
    'शेतातले औषध पोटात गेले',
    'उंदीर मारायचे औषध खाल्ले',
    'vish pyayle ahet',
    'khetatle aushadh potat gele',
    'poisoning zale',
  ],

  // Gastrointestinal & Abdominal
  abdominal_pain: [
    'पोटात दुखतंय',
    'पोटात पीळ पडतोय',
    'पोटात मुरडा होतोय',
    'potat dukhtay',
    'potat peel padtoy',
    'potat murda',
  ],
  severe_abdominal_pain: [
    'पोटात भयंकर कळ मारतेय',
    'पोटात भयंकर कळ',
    'पोटात असह्य भयंकर कळ मारतेय',
    'पोट दगडासारखे कडक झालेय',
    'potat bhayankar vedna',
    'pot dagdasarkhe kadak zale',
  ],
  vomiting: [
    'उलटी होतेय',
    'सारख्या उलट्या होत आहेत',
    'ओकारी येणे',
    'ulti hotey',
    'sarkhya ultya',
    'okari yene',
  ],
  vomiting_blood: [
    'उलटीतून लाल रक्त पडतंय',
    'रक्ताची उलटी होणे',
    'काळ्या रक्ताची ओकारी',
    'ultitun rakt padtay',
    'raktachi ulti hone',
  ],
  diarrhoea: [
    'पातळ जुलाब होत आहेत',
    'पाण्यासारखे संडासला होतेय',
    'वारंवार जुलाब होणे',
    'patal julab hot ahet',
    'sandasla panyasarkhe hone',
  ],
  blood_in_stool: [
    'संडासवाटे रक्त पडतंय',
    'जुलाबातून लाल रक्त जाणे',
    'डांबरासारखी काळी संडास',
    'sandasvate rakt padtay',
    'julabatun rakt jane',
  ],
  severe_dehydration_signs: [
    'डोळे खोल गेलेत जीभ कोरडी पडलीय',
    'शरीरातील पाणी संपले लघवी बंद',
    'dole khol gelet jibh kordi padli',
    'dehydration zale ahe',
  ],
  heartburn: [
    'छातीत जळजळ होतेय',
    'आंबट ढेकर येणे पित्त खवळणे',
    'chatit jaljal hotey',
    'ambat dhekar pitta khavalne',
  ],
  constipation: [
    'बद्धकोष्ठता संडास साफ होत नाही',
    'पोट साफ न होणे',
    'sandas saf hot nahi',
    'baddhakoshthata',
  ],

  // Genitourinary
  cant_pass_urine: [
    'लघवी होत नाहीये',
    'लघवी बंद झालीय',
    'लघवी अडकलीय पोट फुगून कळ मारतेय',
    'laghvi hot nahiye',
    'laghvi band zaliy',
    'laghvi adakli potat kal',
  ],
  pain_urination: [
    'लघवी करताना आग होतेय',
    'लघवीला जळजळ आणि टोचल्यासारखे दुखणे',
    'laghvi kartana aag hotey',
    'laghvit jaljal dukhavat',
  ],
  blood_in_urine: [
    'लघवीतून रक्त येतंय',
    'लाल रंगाची लघवी होणे',
    'laghvitun rakt yetay',
    'laal laghvi hone',
  ],
  scrotal_pain_sudden: [
    'अंडकोषात अचानक भयंकर कळ मारली',
    'गोटी सुजून तीव्र ठसका लागणे',
    'andkoshat achanak dukhavat',
    'goti sujne',
  ],

  // Obstetric & Gynaecological
  pregnancy_bleeding: [
    'गरोदरपणात रक्त जातंय खूप भीती वाटतेय',
    'गरोदरपणात रक्त जातंय',
    'गरोदरपणात रक्तस्राव होतोय',
    'गर्भारपणात रक्त जातंय',
    'दिवस गेलेत आणि अंगावरून लाल जातंय',
    'garodarpanat rakt jatay',
    'divas gelet angavarun rakt',
  ],
  pregnancy_convulsion: [
    'गरोदर स्त्रीला झटके येत आहेत',
    'बाळंतपणात फिट येणे',
    'डिलिव्हरीनंतर झटके येणे',
    'garodarpanat zhatke yetayt',
    'balantpanat fit yene',
  ],
  pregnancy_severe_headache_vision: [
    'गरोदरपणात तीव्र डोकेदुखी डोळ्यापुढे अंधारी',
    'गर्भारपणात डोळे पुसट दिसणे डोके दुखणे',
    'garodarpanat doke dukhoon dhundhla disne',
    'गरोदरपणात डोळे फिरणे आणि तीव्र डोकेदुखी',
  ],
  reduced_fetal_movement: [
    'पोटातले बाळ हालचाल करत नाहीये',
    'गर्भातील बाळाची हालचाल मंदावली',
    'बाळाची लाथ जाणवत नाहीये',
    'potatle baal halchal karat nahiye',
    'halchal mandavli',
  ],
  rupture_of_membranes: [
    'अंगावरून पाणी सुटले अचानक',
    'पाण्याची पिशवी फुटली',
    'angavarun paani sutle',
    'panyachi pishvi futli',
  ],
  labour_pain: [
    'कळा सुरू झाल्या आहेत बाळंतपणाच्या',
    'डिलिव्हरीच्या कळा येणे',
    'कमरेतून पोटात नियमित कळा येणे',
    'kala suru zhalya delivery',
    'balantpanachya kala yetayt',
  ],
  postpartum_bleeding: [
    'बाळंतपणानंतर खूप अंगावरून जातंय',
    'डिलिव्हरीनंतर रक्ताची चिळकांडी थांबेना',
    'balantpananantar khup rakt jane',
    'delivery nantar bleeding thambena',
  ],
  foul_vaginal_discharge: [
    'योनीतून दुर्गंधीयुक्त स्राव येतोय',
    'अंगावरून घाणेरडा वास येणारे पाणी जाणे',
    'durghandhiyukt srav yene',
    'angavarun vaas yenara paani jaatoy',
  ],

  // Paediatric & Neonatal Danger Signs
  infant_not_feeding: [
    'बाळ दूध पीत नाहीये',
    'बाळ स्तनपान करत नाही',
    'लहान बाळ आईचे दूध ओढत नाहीये',
    'baal doodh peet nahiye',
    'baal stanpan karat nahi',
    'navjat baal doodh soodle',
  ],
  infant_lethargy: [
    'लहान बाळ एकदम गळून पडलेय',
    'बाळ हालचाल करत नाही उठत नाही',
    'शिशू अगदी सुस्तावलेला आहे',
    'baal galun padley uthat nahi',
    'infant sust padle ahe',
  ],
  infant_fast_breathing: [
    'बाळाचा श्वास खूप भरभर चाललाय',
    'बाळ धापा टाकतंय पटापट',
    'balacha shwas bharbhar chaltoy',
    'baal dhapa taktay',
  ],
  chest_indrawing: [
    'श्वास घेताना बाळाची छाती आत खचतेय',
    'बाळाच्या बरगड्या आत ओढल्या जातायत',
    'balachi chhati aat khachtey',
    'bargadya aat odhlya jatayt',
  ],
  infant_fever: [
    'दोन महिन्यांच्या आतल्या बाळाला ताप आलाय',
    'नवजात बाळ तापाने फणफणले आहे',
    'navjat balala taap ala ahe',
    'chotya balala taap',
  ],
  infant_hypothermia: [
    'बाळाचे अंग गार पडले आहे बर्फासारखे',
    'नवजात बाळ हाताला खूप थंड लागतंय',
    'balache ang gaar padle ahe',
    'baal thand padne',
  ],
  child_fever: [
    'मुलाला ताप आला आहे',
    'बाळाचे अंग तापाने तापले आहे',
    'mulala taap ala ahe',
    'child fever taap yene',
  ],
  child_ear_pain: [
    'मूल कान चोळून रडतंय',
    'मुलाच्या कानात ठसका आणि वेदना',
    'mool kaan cholun radtay',
    'kanat vedna',
  ],

  // Systemic, Cutaneous & Sensory
  high_fever: [
    'अंग तापाने फणफणलंय',
    'भरपूर ताप भरलाय हुडहुडी भरून',
    'खूप कडक ताप येणे',
    'ang tapane fanfanlay',
    'hudhudi bharun taap yene',
    'kadak taap',
  ],
  fever_with_stiff_neck: [
    'तापासोबत मान ताठ झालीय वाकवता येत नाही',
    'तापात मान कडक होणे हनुवटी छातीला लागत नाही',
    'tapasobat maan tath zaliy',
    'maan kadak hone tapasobat',
  ],
  fever_with_petechial_rash: [
    'तापासोबत अंगावर जांभळे लाल डाग उठले',
    'तापात त्वचेवर न मिटणारे काळे डाग',
    'tapasobat angavar lal jambhle daag',
    'angavar tapasobat lal chatte disat aahet',
  ],
  severe_allergic_reaction: [
    'चेहरा ओठ सुजले आणि धाप लागतेय',
    'काहीतरी चावल्याने तोंड सुजून गळा आवळल्यासारखा',
    'chehra oth sujne dhap lagne',
    'allergic reaction tond sujne',
  ],
  body_ache: [
    'सर्व अंग दुखतंय कणकण भरलीय',
    'हातपाय गळून गेलेत हाडे दुखतात',
    'sarva ang dukhtay kankan',
    'hatpay ghalun jane',
  ],
  weakness_fatigue: [
    'खूप जास्त अशक्तपणा आलाय',
    'उभे राहण्याची ताकद उरली नाही',
    'khup jast ashaktapana',
    'takad urli nahi uthayla',
  ],
  skin_rash: [
    'अंगावर खाजवणारे लाल पुरळ',
    'त्वचेवर गांधी उठणे',
    'angavar lal pural khaj yene',
    'skin rash gandhi uthne',
  ],
  joint_pain: [
    'सांधे दुखत आहेत',
    'गुडघे दुखणे आणि सुजणे',
    'sandhe dukhat ahet',
    'gudghe dukhan sujne',
  ],
  eye_injury: [
    'डोळ्याला मार लागला',
    'डोळ्यात काहीतरी टोकदार गेले किंवा औषध उडाले',
    'dolyala maar lagla',
    'dolyat kachra gela',
  ],
  eye_redness_pain: [
    'डोळा लाल झालाय पाणी आणि चिकटा येतोय',
    'डोळ्यात तीव्र आग आणि खुपणे',
    'dola lal zala ahe aag hone',
    'dolyat dukhtay ani lal disatoy',
  ],
  ear_discharge: [
    'कानातून पू वाहतोय',
    'कान वाहणे घाण वास येणे',
    'kanatun poo vahtoy',
    'kaan vahte',
  ],
  sore_throat: [
    'घसा दुखतोय गिळताना त्रास होतोय',
    'घशात खवखव आणि टोचणे',
    'ghasa dukhtoy gilatana tras',
    'ghashat khavkhav',
  ],
};