import type { SupportedLanguage } from '../types';

export const NEGATION_CUES: Record<SupportedLanguage, readonly string[]> = {
  en: [
    'no',
    'not',
    'without',
    'never',
    'denies',
    'denied',
    'negative for',
    'free of',
    'nil',
    "didn't have",
    "doesn't have",
    "don't have",
    'neither',
    'nor',
  ],
  hi: [
    'नहीं',
    'नही',
    'ना',
    'बिना',
    'गैर',
    'nahi',
    'nahin',
    'nahe',
    'bina',
    'koi nahi',
    'kuch nahi',
  ],
  mr: [
    'नाही',
    'नाय',
    'नाहित',
    'नाहीत',
    'नाहीये',
    'नाहीयेत',
    'नसून',
    'विना',
    'शिवाय',
    'nahi',
    'nahit',
    'nahiye',
    'naay',
    'shivaay',
  ],
};

export const CLAUSE_BREAKS: Record<SupportedLanguage, readonly string[]> = {
  en: [',', '.', ';', '!', '?', 'but', 'however', 'although', 'except', 'yet'],
  hi: [
    ',',
    '.',
    '।',
    ';',
    '!',
    '?',
    'लेकिन',
    'परंतु',
    'मगर',
    'किंतु',
    'पर',
    'तथापि',
    'lekin',
    'parantu',
    'magar',
    'par',
  ],
  mr: [
    ',',
    '.',
    '।',
    ';',
    '!',
    '?',
    'पण',
    'परंतु',
    'मात्र',
    'तरी',
    'किंवा',
    'तथापि',
    'pan',
    'parantu',
    'matra',
    'tari',
  ],
};

/** Maximum tokens a negation cue can project forward within a clause */
export const NEGATION_SCOPE_LIMIT = 4;
